name: Build Android
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Build Android Release
        run: cd FrontEnd

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: FrontEnd
